// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VanPhongVanchuyenBacNam.Data;

#nullable disable

namespace VanPhongVanchuyenBacNam.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260610132807_AddShipments")]
    partial class AddShipments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("VanPhongVanchuyenBacNam.Models.Shipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("CODAmount")
                        .HasColumnType("decimal(18,0)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveredDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoodsDescription")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("RecipientAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("RecipientName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RecipientPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RecipientProvince")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SenderName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SenderPhone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,0)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("TransportCompanyId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("TrackingCode")
                        .IsUnique();

                    b.HasIndex("TransportCompanyId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("VanPhongVanchuyenBacNam.Models.TransportCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BackupPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("TransportCompanies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Bến xe Vĩnh Niệm, Hải Phòng",
                            BackupPhone = "0912 245 245",
                            ContactPerson = "Anh Long",
                            IsActive = true,
                            Name = "Nhà xe Hoàng Long",
                            Note = "Nhận hàng cồng kềnh",
                            PhoneNumber = "0225 392 0920",
                            Province = "Hải Phòng"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bến xe Vinh, Nghệ An",
                            ContactPerson = "Chị Hoa",
                            IsActive = true,
                            Name = "Nhà xe Văn Minh",
                            PhoneNumber = "0238 383 8383",
                            Province = "Nghệ An"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Bến xe Miền Đông, TP. Hồ Chí Minh",
                            IsActive = true,
                            Name = "Nhà xe Phương Trang",
                            PhoneNumber = "0283 838 6852",
                            Province = "TP. Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 4,
                            ContactPerson = "Anh Tuấn",
                            IsActive = true,
                            Name = "Nhà xe Hải Âu",
                            Note = "Tuyến Hà Nội - Hải Phòng, nhiều chuyến mỗi ngày",
                            PhoneNumber = "0225 374 7474",
                            Province = "Hải Phòng"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Bến xe phía Nam Nha Trang",
                            IsActive = true,
                            Name = "Nhà xe Quang Hạnh",
                            PhoneNumber = "0258 381 2812",
                            Province = "Khánh Hòa"
                        },
                        new
                        {
                            Id = 6,
                            IsActive = false,
                            Name = "Nhà xe Ba Miền",
                            Note = "Tạm ngừng hợp tác từ 5/2026",
                            PhoneNumber = "0236 362 6262",
                            Province = "Đà Nẵng"
                        });
                });

            modelBuilder.Entity("VanPhongVanchuyenBacNam.Models.Shipment", b =>
                {
                    b.HasOne("VanPhongVanchuyenBacNam.Models.TransportCompany", "TransportCompany")
                        .WithMany()
                        .HasForeignKey("TransportCompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TransportCompany");
                });
#pragma warning restore 612, 618
        }
    }
}
